module.exports={
    MAIN_TAB:'主页',
    DELIVER_TO: '配送至',
    //Searching
    AREA_SEARCH:'分区&搜索',
    CITY_AREA:'城市&区域',
    RES_TAG:'餐厅分类',
    //Setting
    MY_TAB:'我的',
    SETTING:'设置',
    MY_ORDER:'我的订单',
    ADD_ADDRESS:'添加地址',
    SAVE_ADDRESS:'保存地址',
    CUSTOMER_SERVICE:'联系客服',
    SWEETBOX: '甜满箱 首单立减8刀 满60再减10刀',
    LOG_OUT: '退出登录',

    //Order
    ORDER:'点餐',
    ALL_ORDER:'全部订单',
    COMMENT:'评价',
    YET_COMMENT:'待评价',
    ORDER_NO:'订单号',
    PRICE:'总价',
    ACTUAL_PICE:'实付',
    VERTIFICATION_CODE:'获取验证码',
    NEW_CONFIRMING:'新用户订单确认中',
    ENTER_VERTIFICATION_CODE:'请输入验证码',
    RECIPT:'收据',
    HELP:'帮助',
    SOLD_OUT:'售完',
    REORDER:'重新下单',
    DETAIL:'详情',
    DISH_QUANTITY:'菜品数量',
    //Address
    ADDRESS:'地址',
    CONFIRM:'确认',
    CHOOSE_ADDRESS:'请选择地址',
    DELETE_ADDRESS:'删除地址',
    ENTER_ADDRESS:'输入地址',
    CHOOSE:'请选择',
    ADD_DEFAULT_ADDRESS:'设置为默认地址(选填)',

    //Info
    CONTACT:'联系人',
    PHONE:'电话',


    //Check out
    GO_CHECKOUT:'去结账',
    ADD_PAYMENT:'添加支付方式',
    PICK_UP:'现金自取',
    DELIVER:'送餐',
    SET_DELIVER_FEE:'定制运费',
    CHECK_OUT:'结账',
    DELIVER_FEE:'运费',
    PAY:'支付',
    REMARK:'备注',
    ADD_REMARK:'添加备注（例如：忌口、过敏）',
    TIPS:'小费',
    TAXED_PRICE:'税后价格',
    PRETAX_PRICE:'税前价格',

    //Comment
    CONFIRM_COMMENT:'确认评价',
    CANCEL:'取消',
    CHANGE_COMMENT:'更正',
    RATE_DELIVERY:'为配送打分',
    COMMENT_PLACEHOLDER:"写下您对司机的评价吧~",
    RESTAURANT_PLACEHOLDER:"写下您对商家的评价吧~",
    PLEASE_COMMENT:"请对送餐司机和餐馆打分",
    LIKE:'赞',
    DISLIKE:'踩',
    COMMENT:"评价",
    CM_DELIVERY: '馋猫专送',
    COMPLETE_TIME_PREFIX:'当日',
    COMPLETE_TIME_SUFFIX:'左右送达',
    ON_TIME:'准时',
    POLITE:"有礼貌",
    QUICK:"速度快",
    WELL_SERVERED:"服务周到",
    DELIVERY_TO_DOOR:"送货上门",
    WARM_DISH:"保温",
    WELL_PACKAGING:"包装完整",
    NICE_PACKAGING:"包装精美",
    WORTHY:"物美价廉",
    TASTY:"口味好",
    ECONOMICAL:"实惠",
    LARGE_AMOUNT:"分量足",


    //Card Type
    CREDIT_CARD:'信用卡',
    DEBIT_CARD:'借记卡',
    ALIPAY:'支付宝',
    CASH:'到付(现金/刷卡)',
    PAYMENT_TYPE:"支付方式",
    //About us
    ABOUT_US:'关于我们',

}
