module.exports={
  MAIN_TAB:'Home',
  MY_TAB:'My',
  CART:'Cart',
  ALERT_MESSAGE:'Our delivery range has expanded as the picture shows, including all condos and houses. You can confirm the validation of your address when you check out.',

  MY_ORDER:'My Order',
  CUSTOMER_SERVICE:'Contact Us',
  CM_EAT:'Chanmao Eats',
  LOG_OUT:'Log Out',
  //SboxAddAddress
  ADDRESS_SEARCH:'Search Address',
  //SboxAddAddressInfo
  ADD_NAME:'Name::',
  FILL_NAME_IN_ENGLISH:'Fill Your Name in English',
  ADD_PHONE:'Tel: +1 ',
  ADD_UNIT:'Unit No.: ',
  ADD_ADDRESS:'Add Address',
  INFO_NOTE1:'Note：1. Write your name in English. Please provide your phone number and legal name for picking up the packages at concierge, otherwise your packages will be rejected.',
  INFO_NOTE2:"2. If you live in condo, Sweetful box will be delivered to your concierge. If your condo dosen't have a concierge, our driver will contact you while arriving. Please make sure we can reach you in time. Thanks",
  ALERT_ERROR:'Something Wrong',
  ALERT_UNCOMPLETE:'Please Enter All Information',
  ALERT_PHONE:'You Entered a Wrong Phone Number',
  //SboxAddCard
  CARD_NUMBER:'Card Number',
  EXPIRE_DATE:'Expire Date',
  SWEETFUL_BOX:'Sweetful Box',
  PAYMENT_INFO_ERROR:'Invalid Payment Information',
  ADD_CREDIT:'Add Credit Card',
  ADD_DEBIT:'Add Debit Card',
  PAYMENT_METHOD:'Payment Method',
  CREDIT_CARD:'Credit Card',
  //SboxAddressList
  ADDRESS:'Address',
  DELIVERY_RANGE:'我们只配送以下范围， 请选择您收货的Condo地址',
  //SboxCart
  OUT_OF_STOCK:'Out of Stock',
  MINIMUM_BEFORE_TAX:'Deliver on order over $25',
  DELETE:'Delete',
  CANCEL:'Cancel',
  CONFIRM:'Confirm',
  CART_BOX:'Cart',
  //SboxCategory
  PRODUCT_CATEGORY:'Product Category',
  SEARCH_RECORD:'Search Record',
  CLEAN:'Clear',
  SEARCH:'Search',
  //SboxCheckout
  ADD_DELIVERY_ADDRESS:'Add Address',
  ADD_PAYMENT_METHOD:'Add Payment Method',
  SELECT_DELIVERY_ADDRESS:'Select Delivery Address',
  CARD_NUMBER:'Card Number',
  //SbooxHistory
  CONFIRMED:'Confirmed',
  PACKAGE:'Packing',
  DELIVERING:'Delivering',
  DELIVERED:'Delivered',
  COMPLETE:'Complete',
  ORDER_NUMBER:'  No.:  #',
  COPYED:'Copied',
  CUSTOMER_SERVICE_WECHAT:'Customer Service WeChat: sweetfulinc',
  DELIVERY_FEE:'Delivery Fee: $11111',
  ORDER_TOTAL:'Total: $',
  DETAIL:'Detail',
  SERVICE:'Customer Service',
  //SboxHistoryOrderDetail
  ORDER_DETAIL:'Order Detail',
  //SboxNotification
  CONGRATS:'Congratulations!',
  ORDER_SUCCESS:'Order Success',
  PAYMENT_SUCCESS:'Payment Success! Your box will arrive in 2 Working days.',
  HISTORY_ORDER:'View History Orders',
  ORDER_FAILED:'Order Failed',
  SORRY_MESSAGE:'Sorry',
  PAYMENT_FAILED:'Order failed! Please check your address and payment information. If you need help, please contact customer service.',
  RETURN_TO_CART:'Return to Cart',
  //SboxProductDetail
  QUANTITY:'Quantity',
  ADD_TO_CART:'Add to Cart',
  SERVICE_DETAIL:'Service Detail',
  UNIT:'item(s)',
  GO_CHECKOUT:'Check out',
  DERLIVER_TIME:'Delivery Time',
  COMMENT:'Comment',
  ADD_COMMENT:'Add Comment',
  WITHIN_TWO_DAY:'within Two Working Days',
}
