module.exports={
  MAIN_TAB:'首页',
  MY_TAB:'我的',
  CART:'购物车',
  ALERT_MESSAGE:'我们的配送范围已扩大至图中红框区域，包括所有Condo或House均可送达~具体地址可在填写订单时确认。',

  MY_ORDER:'我的订单',
  CUSTOMER_SERVICE:'联系客服',
  CM_EAT:'馋猫订餐',
  LOG_OUT:'登出',
  //SboxAddAddress
  ADDRESS_SEARCH:'搜索地址',
  //SboxAddAddressInfo
  ADD_NAME:'联系人: ',
  FILL_NAME_IN_ENGLISH:'请以英文拼写您的姓名',
  ADD_PHONE:'电话: +1 ',
  ADD_UNIT:'Unit No.: ',
  ADD_ADDRESS:'添加地址',
  INFO_NOTE1:'注：1. 请以英文形式拼写您的姓名，所留姓名和电话请务必与您所在的Condo前台登记的信息一致，否则包裹会被前台拒收。',
  INFO_NOTE2:'2. 甜满箱包裹会配送到您的Condo前台。如果您所在的Condo没有前台，我们的配送员会在到达后电话联系您取包裹。请您保持电话畅通，谢谢。',
  ALERT_ERROR:'错误',
  ALERT_UNCOMPLETE:'请填写所有信息',
  ALERT_PHONE:'手机号码格式错误',
  //SboxAddCard
  CARD_NUMBER:'信用卡号',
  EXPIRE_DATE:'有效期至',
  SWEETFUL_BOX:'甜满箱',
  PAYMENT_INFO_ERROR:'您输入的支付信息输入有误',
  ADD_CREDIT:'添加信用卡',
  ADD_DEBIT:'添加 Debit Card',
  PAYMENT_METHOD:'支付方式',
  CREDIT_CARD:'信用卡',
  //SboxAddressList
  ADDRESS:'地址',
  DELIVERY_RANGE:'我们只配送以下范围， 请选择您收货的Condo地址',
  //SboxCart
  OUT_OF_STOCK:'库存不足',
  MINIMUM_BEFORE_TAX:'税前满$25起送',
  DELETE:'删除',
  CANCEL:'取消',
  CONFIRM:'确认',
  CART_BOX:'购物箱',
  //SboxCategory
  PRODUCT_CATEGORY:'产品分类',
  SEARCH_RECORD:'搜索记录',
  CLEAN:'清空',
  SEARCH:'搜索',
  //SboxCheckout
  ADD_DELIVERY_ADDRESS:'添加配送地址',
  ADD_PAYMENT_METHOD:'添加支付方式',
  SELECT_DELIVERY_ADDRESS:'请选择您的配送地址',
  CARD_NUMBER:'卡号',
  //SbooxHistory
  CONFIRMED:'已确认',
  PACKAGE:'打包中',
  DELIVERING:'配送中',
  DELIVERED:'已送达',
  COMPLETE:'已完成',
  ORDER_NUMBER:'  订单号:  #',
  COPYED:'已复制',
  CUSTOMER_SERVICE_WECHAT:'甜满箱客服微信: sweetfulinc',
  DELIVERY_FEE:'运费: $11111',
  ORDER_TOTAL:'总价: $',
  DETAIL:'详情',
  SERVICE:'客服',
  //SboxHistoryOrderDetail
  ORDER_DETAIL:'订单详情',
  //SboxNotification
  CONGRATS:'恭喜您',
  ORDER_SUCCESS:'订单成功',
  PAYMENT_SUCCESS:'订单支付成功！您可以在两个工作日内收到您的箱子~',
  HISTORY_ORDER:'查看历史订单',
  ORDER_FAILED:'订单失败',
  SORRY_MESSAGE:'很抱歉',
  PAYMENT_FAILED:'订单支付失败了！请仔细核对您的地址或银行卡信息是否准确，如需人工帮助，请您联系客服，谢谢！',
  RETURN_TO_CART:'返回购物箱',
  //SboxProductDetail
  QUANTITY:'数量',
  ADD_TO_CART:'加入购物箱',
  SERVICE_DETAIL:'服务明细',
  UNIT:'件',
  GO_CHECKOUT:'去结账',
}
