module.exports ={
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    INCREASE_ITEM:'INCREASE_ITEM',
    DECREASE_ITEM:'DECREASE_ITEM',
    //chanmao login api,{username: , password: }
    API_LOGIN:'http://www.chanmao.ca/index.php?r=MobLogin/login',
    API_AUTH:'http://www.chanmao.ca/index.php?r=MobLogin/loginwc',
    ERROR_PASSWORD:'ERROR_PASSWORD',
    ERROR_PASSWORD_MESSAGE:'密码不正确',
    ERROR_NETWORK:'ERROR_NETWORK',
    ERROR_NETWORK_MESSAGE:'请检查您的网络',
    ERROR_STORE:'请重新登录',
    ERROR_AUTH:'请重新登录',
    SUCCESS_LOGIN:'登录成功',
    //wechat
    WECHAT_SCOPE:'snsapi_userinfo',
    WECHAT_STATE:'wechat_sdk_test',
    WECHAT_APPID:'wx20fd1aeb9b6fcf82',

    //auth
    SUCCESS: 1,
    FAIL: 0,
    TOKEN:'userToken',
    UID:'sv_uid',
    LOGOUT:'LOGOUT',

    // auth
    DO_LOGIN:'DO_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    ERRROR_TITLE:'出错啦',

    // History
    GET_HISTORY_SUCCESS:'GET_HISTORY_SUCCESS',
    GET_HISTORY_DETAIL:'GET_HISTORY_DETAIL',
    GET_ORDERS:'GET_ORDERS',
    REVIEW_ADDED:'REVIEW_ADDED',

    //Restaurant
    GET_RESTAURANT_SUCCESS:'GET_RESTAURANT_SUCCESS',
    GET_MENU_SUCCESS:'GET_MENU_SUCCESS',
    GET_RESTAURANT_BY_TAG:'GET_RESTAURANT_BY_TAG',
    GET_TAG:'GET_TAG',
    // address
    PREDICTIONS_SUCCESS:'PREDICTIONS_SUCCESS',
    GET_ADDRESSES:'GET_ADDRESSES',
    FORMAT_ADDRESS:'FORMAT_ADDRESS',
    SUBMIT_ADDRESS:'SUBMIT_ADDRESS',
    UPDATE_SELECTED_ADDRESS:'UPDATE_SELECTED_ADDRESS',
    UPDATA_ADDRESSLIST:'UPDATA_ADDRESSLIST',
    UPDATA_SELECTED_UAID:'UPDATA_SELECTED_UAID',
    UPDATA_ADDRESS_STATUS:'UPDATA_ADDRESS_STATUS',
    UPDATA_CURRENT_LOCATION:'UPDATA_CURRENT_LOCATION',
    CLEAR_ADDRESS_INPUT:'CLEAR_ADDRESS_INPUT',
    DISMISS_ADDRESS_PROMPT:'DISMISS_ADDRESS_PROMPT',

    //alert
    ALERT_TITLE:'馋猫订餐',
    STARTED:'正在执行中',

    // order
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    INCREASE_ITEM:'INCREASE_ITEM',
    DECREASE_ITEM:'DECREASE_ITEM',
    REORDER:'REORDER',
    UPDATE_TOPPING: 'UPDATE_TOPPING',
    DECREASE_TOPPING_QUANTITY: 'DECREASE_TOPPING_QUANTITY',
    UPDATE_PRODUCT_QTY: 'UPDATE_PRODUCT_QTY',
    ADD_CARD:'ADD_CARD',

    // Checkout
    BEFORE_CHECKOUT:'BEFORE_CHECKOUT',
    CALCULATE_DELIVERY_FEE:'CALCULATE_DELIVERY_FEE',
    CHECKOUT:'CHECKOUT',
    UPDATE_ADDRESS:'UPDATE_ADDRESS',
    UPDATE_DLTYPE:'UPDATE_DLTYPE',
    UPDATE_PAYMENT_STATUS:'UPDATE_PAYMENT_STATUS',
    SHOULD_ADD_ADDRESS: 'SHOULD_ADD_ADDRESS',
    VERIFY_PHONE:'VERIFY_PHONE',

    // The Six
    GET_ATICLE_LIST:'GET_ATICLE_LIST',
    GET_ARTICLE_AUTHOR:'GET_ARTICLE_AUTHOR',
    GET_BROADCAST_AUTHOR:'GET_BROADCAST_AUTHOR',
    GET_ACTIVITY_AUTHOR:'GET_ACTIVITY_AUTHOR',
    SUBMIT_APPLICATION:'SUBMIT_APPLICATION',
    SUBMIT_COMMENT:'SUBMIT_COMMENT',
    GET_COMMENT_AMOUNT:'GET_COMMENT_AMOUNT',
    GET_COMMENT_LIST:'GET_COMMENT_LIST',
    CHECK_UPDATE:'CHECK_UPDATE',


    //Home
    GET_HOME_DATA:'GET_HOME_DATA',

    //TabsStore
    GO_TO_HISTORY:'GO_TO_HISTORY',

    //api key
    GOOGLE_API_KEY:'AIzaSyDpms3QxNnZNxDq5aqkalcRkYn16Kfqix8',
    CM_VERSION:'2.6.1',
}
