module.exports ={

    // address
    GET_CONDO_LIST: 'GET_CONDO_LIST',
    GET_CONDO_FUZZY: 'GET_CONDO_FUZZY',
    // product
    GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',
    GET_HOME_DATA: 'GET_HOME_DATA',
    SEARCH_THEME_LIST: 'SEARCH_THEME_LIST',
    SEARCH_CATEGORY_LIST: 'SEARCH_CATEGORY_LIST',
    GET_CATEGORY_LIST: 'GET_CATEGORY_LIST',
    // Manage
    GET_DAILY_REDIS: 'GET_DAILY_REDIS',
    // Order
    GET_ORDER_BEFORE: 'GET_ORDER_BEFORE',
    // User
    GET_ORDER_HISTORY: 'GET_ORDER_HISTORY',
    PUT_USER_ADDR: 'PUT_USER_ADDR',

    SBOX_VERSION: '2.3.4',
};
