module.exports={
    MAIN_TAB:'Home',
    DELIVER_TO: 'Deliver to',
    //Searching
    AREA_SEARCH:'Category&Search',
    CITY_AREA:'City&Area',
    RES_TAG:'Category',
    MORE_TYPE:'More Categories',
    RETRACT:'Retract',
    //Setting
    MY_TAB:'My',
    SETTING:'Settings',
    MY_ORDER:'My Order',
    ADD_ADDRESS:'Add Address',
    SAVE_ADDRESS:'Save Address',
    CUSTOMER_SERVICE:'Contact Us',
    LANGUAGE_SETTING: 'Select Language',
    SWEETBOX: 'Sweetful Box, free shipping with purchase over $25',
    LOG_OUT: 'Log Out',

    //Order
    ORDER:'Order',
    ALL_ORDER:'All Orders',
    COMMENT:'Comments',
    YET_COMMENT:'Add Comments',
    ORDER_NO:'No.',
    PRICE:'Total',
    ACTUAL_PICE:'Actual Total',
    VERTIFICATION_CODE:'Get Code',
    NEW_CONFIRMING:'New User to be Confirmed',
    ENTER_VERTIFICATION_CODE:'Enter Code',
    RECIPT:'Recipt',
    HELP:'Help',
    SOLD_OUT:'Sold Out',
    REORDER:'Reorder',
    DETAIL:'Detail',
    DISH_QUANTITY:'Dish Quantity',
    //Address
    ADDRESS:'Address',
    CONFIRM:'Comfirm',
    CHOOSE_ADDRESS:'Select Address',
    DELETE_ADDRESS:'Delet Address',
    ENTER_ADDRESS:'Enter Address',
    CHOOSE:'Select One',
    ADD_DEFAULT_ADDRESS:'Set as Default Address(Optional)',

    //Info
    CONTACT:'Name',
    PHONE:'Phone',


    //Check out
    ADD_PAYMENT:'Add Payment Method',
    PICK_UP:'Pick up',
    DELIVER:'Deliver',
    SET_DELIVER_FEE:'Set Delivery Fee',
    CHECK_OUT:'Check out',
    DELIVER_FEE:'Delivery Fee',
    PAY:'Payment',
    ONLINE_PAYMENT_WARNING: 'No refunds will be processed for customers that place orders through 3rd party WeChat services. Suspicious activities will be submitted to the police for investigation.',
    REMARK:'Remark',
    ADD_REMARK:'Add Remark(extra sauce, allergic)',
    TIPS:'Tips',
    TAXED_PRICE:'Price after Tax',
    PRETAX_PRICE:'Price before Tax',
    PRICE_SUBTOTAL:'Price Subtotal',
    PROMOTION:'Promotion',
    DISCOUNT:'Discount',
    CURRENT_USING:'Using',
    USE:'Apply',
    COUPON_CODE:'Promotion Code',
    COUPON_CODE_INVALID_REMINDER:'*Coupon Code not available, Cannot be used in this situation',
    INVALID_COUPON_CODE:'Invalid Coupon Code, Please Check and Retry',
    TAX:'Tax',
    SERVICE_FEE:'Service Fee',
    SERVICE_FEE_REMINDER:'No Extra Tips',
    CHARGE_TOTAL:'Charge',
    ACTUAL_PAYING:'Final Price',
    CONFIRM_ORDER:'Confirm Order',
    CONFIRM_PAY:'Confirm to Pay',
    RECENTLY_USE:'Recently Use',
    MORE_PAYMENT_WAY:'More Payment Methods',
    LONG_D_ORDER_REMINDER:"*Long Distance Delivery Order. Please check the restaurant and delivery address.(Online payment order will be charged later.)",
    ALERT_ERROR_TITLE:'Something Wrong',
    CONFIRM_DELETE:'Confirm to Delete',
    PLZ_ENTER_COUPON:'Enter Promotion Coupon',
    ALERT_SERVICE_FEE_REMINDER:"Service fee contains online payment poundage, (includes credit card, debit card, Apple Pay and Alipay)and driver's service fee. No need to pay extra tips.",
    REMINDING:'Notice',
    ADD_CREDIT_CARD:'Add Credit Card',
    ADD_DEBIT_CARD:'Add Debit Card',
    CARD_NUMBER:'Card No.',
    EXPIRED_AT:'Expire Date',

    //Menu
    GO_CHECKOUT:'Check Out',
    OPTION:'Option',
    RESTAURANT_CLOSED:'Restaurant Closed',
    RESTAURANT_CLOSED_LAH:'Restaurant Closed',
    ADD:'Add',
    UNIT:'item(s)',
    SEARCH_RESTAURANTS_PLACEHOLDER:'Search Restaurants',
    CANNOT_FIND_ABOUT:'Cannot Find anything about',
    ABOUT_XX_ITEMS:'',
    SEARCH:'Search',

    //Login & Register & ResetPassword
    PLZ_ENTER_ACC_INFO: 'Please Enter Account Information',
    INVALID_PASSWORD_LENGTH:'Password Must between 8 to 32 words',
    LOGIN_FAILED:'Fail to Login, Please Check the Information',
    PASSWORD_NOT_MATCHING:'Password Not Matching, Please Enter Again',
    PLZ_ENTER_PHONE_NUM: 'Please Enter the Correct Phone Number',
    ALERT_CONGRA_TITLE:'Congratulation!',
    PASSWORD_RESET_SUCCESS:'Password Reset Success',
    PLZ_ENTER_PASSWORD:'Please Enter Password',
    PASSWORD_NOT_THE_SAME:'Password not Matching',

    //History
    PAID:'Paid',
    WAIT_FOR_RR_CONFIRM:'Waiting Restaurant to Confirm',
    REFUNDED:'Refunded',
    ONLINE_PAYMENT_FAILED:'Online Payment Failed',
    PLZ_REORDER:'Please Reorder',
    WAIT_FOR_PAYMENT:'Wait for Payment',
    WAIT_FOR_PAYMENT_REMINDER:'If the Status not Change in Time, Pull Down to Refresh',
    RESTAURANT_CONFIRMED:'Restaurant Confirmed',
    PLZ_PICKUP:'Please Pick up',
    GETTING_RDY:'Getting Ready',
    DRIVER_IS_OTW:'Driver on the Way',
    DELIVERED:'Delivered',
    NEW_USER_CONFIRMING:'New User Needs to be Confirmed',
    CS_WILL_CONTACT:'Customer Service Will Contact you about the Delivery Fee',
    DISH_OUT_OF_ORDER:'Dish is out of Order',
    ORDER_CANCELED:'Order Canceled',

    //Comment
    CONFIRM_COMMENT:'Confirm',
    CANCEL:'Cancel',
    CHANGE_COMMENT:'Change Comment',
    RATE_DELIVERY:'Please Rate the Delivery',
    COMMENT_PLACEHOLDER:"Please Write Comments to Our Driver",
    RESTAURANT_PLACEHOLDER:"Please Write Comments to the Restaurant",
    PLEASE_COMMENT:"Please Write Comments to Our Driver and Restaurant",
    LIKE:'Like',
    DISLIKE:'Dislike',
    COMMENT:"Comment",
    CM_DELIVERY: 'Chanmao Driver',
    COMPLETE_TIME_PREFIX:'Today',
    COMPLETE_TIME_SUFFIX:'Arrived',
    ON_TIME:'On Time',
    POLITE:"Polite Service",
    QUICK:"Quick",
    WELL_SERVERED:"Well Servered",
    DELIVERY_TO_DOOR:"Delivery to Door",
    WARM_DISH:"Warm Dishes",
    WELL_PACKAGING:"Well Packed",
    NICE_PACKAGING:"Nice Packed",
    WORTHY:"Worthy",
    TASTY:"Tasty",
    ECONOMICAL:"Reasonable Prices",
    LARGE_AMOUNT:"Plentiful",


    //Card Type
    CREDIT_CARD:'Credit Card',
    DEBIT_CARD:'Debit Card',
    ALIPAY:'Alipay',
    CASH:'Cash',
    CASH_SELF_PICKUP:'Pick up',
    CARD:'Card',
    APPLE_PAY:'Apple Pay',
    PAYMENT_TYPE:"Payment Method",
    //About us
    ABOUT_US:'About Us',
    CHANMAO_INFO:'这是一个致力于打造多伦多最佳订餐平台，为自己理想奋斗的热血团队。我们愿真诚的接纳您的意见，也邀请志同道合的你加入我们。',
    CHANMAO_KEFU:'微信客服：chanmao_kefu',
    CHANMAO_BUSINESE:'商务合作：marketing@chanmao.ca',
    CHANMAO_COPYRIGHT:'Chanmao Inc. 版权所有',
    APP_VERSION:'版本号',

    //ALERT_TITLE
    ALERT_TITLE:'Chanmao',
    ALERT_CONTENT:'The Information You Entered is not Correct',
    //HomeTab
    ORDER_BELOW:'Push to Order',
    //MAIN_TAB
    ALERT_PAYMENT:"*Notice: From now on we don't accept payment by card with drivers, and don't use Email Transfer as well. You can use online payment, including Visa, Mastercard, Debit Card, Apple Pay and Alipay, or cash. Thanks.",
    ALERT_COMFIRM:'Confirm',
    COMFIRM_ADDRESS:'Is this the correct address？Seems far from your current location.'
}
