module.exports={
    MAIN_TAB:'主页',
    DELIVER_TO: '配送至',
    //Searching
    AREA_SEARCH:'分区&搜索',
    CITY_AREA:'城市&区域',
    RES_TAG:'餐厅分类',
    MORE_TYPE:'更多分类',
    RETRACT:'收起',
    //Setting
    MY_TAB:'我的',
    SETTING:'设置',
    MY_ORDER:'我的订单',
    ADD_ADDRESS:'添加地址',
    SAVE_ADDRESS:'保存地址',
    CUSTOMER_SERVICE:'联系客服',
    LANGUAGE_SETTING: '选择语言',
    SWEETBOX: '甜满箱 全场免运费 满$25起送',
    LOG_OUT: '退出登录',

    //Order
    ORDER:'点餐',
    ALL_ORDER:'全部订单',
    COMMENT:'评价',
    YET_COMMENT:'待评价',
    ORDER_NO:'订单号',
    PRICE:'总价',
    ACTUAL_PICE:'实付',
    VERTIFICATION_CODE:'获取验证码',
    NEW_CONFIRMING:'新用户订单确认中',
    ENTER_VERTIFICATION_CODE:'请输入验证码',
    RECIPT:'收据',
    HELP:'帮助',
    SOLD_OUT:'售完',
    REORDER:'重新下单',
    DETAIL:'详情',
    DISH_QUANTITY:'菜品数量',
    //Address
    ADDRESS:'地址',
    CONFIRM:'确认',
    CHOOSE_ADDRESS:'请选择地址',
    DELETE_ADDRESS:'删除地址',
    ENTER_ADDRESS:'输入地址',
    CHOOSE:'请选择',
    ADD_DEFAULT_ADDRESS:'设置为默认地址(选填)',

    //Info
    CONTACT:'联系人',
    PHONE:'电话',


    //Check out
    ADD_PAYMENT:'添加支付方式',
    PICK_UP:'现金自取',
    DELIVER:'送餐',
    SET_DELIVER_FEE:'定制运费',
    CHECK_OUT:'结账',
    DELIVER_FEE:'运费',
    PAY:'支付',
    ONLINE_PAYMENT_WARNING:'使用微信代叫，刷假卡造成的订单取消平台将不予退款，可疑账户平台会配合警方调查',
    REMARK:'备注',
    ADD_REMARK:'添加备注（例如：忌口、过敏）',
    TIPS:'小费',
    TAXED_PRICE:'税后价格',
    PRETAX_PRICE:'税前价格',
    PRICE_SUBTOTAL:'订单小计',
    PROMOTION:'优惠',
    DISCOUNT:'折扣',
    CURRENT_USING:'正在使用',
    USE:'使用',
    COUPON_CODE:'折扣码',
    COUPON_CODE_INVALID_REMINDER:'*折扣码条件不满足 无法在当前使用',
    INVALID_COUPON_CODE:'优惠码无效，请检查重试',
    TAX:'税',
    SERVICE_FEE:'服务费',
    SERVICE_FEE_REMINDER:'无需再付小费',
    CHARGE_TOTAL:'总计',
    ACTUAL_PAYING:'实付',
    CONFIRM_ORDER:'确认订单',
    CONFIRM_PAY:'确认支付',
    RECENTLY_USE:'最近使用',
    MORE_PAYMENT_WAY:'更多方式',
    LONG_D_ORDER_REMINDER:'*此单为远距离配送，请核对餐厅地址及送餐地址是否正确(在线支付等待确认后扣款)',
    ALERT_ERROR_TITLE:'错误',
    CONFIRM_DELETE:'确认删除',
    PLZ_ENTER_COUPON:'请输入优惠码',
    ALERT_SERVICE_FEE_REMINDER:'服务费已包含线上支付手续费（只有使用信用卡，借记卡，Apple Pay和支付宝的时候才会产生）和司机服务费，无需再支付小费。',
    REMINDING:'提示',
    ADD_CREDIT_CARD:'添加信用卡',
    ADD_DEBIT_CARD:'添加银行卡',
    CARD_NUMBER:'卡号',
    EXPIRED_AT:'有效期至',
    DELIVER_ADDRESS:'送餐地址',

    //Menu
    GO_CHECKOUT:'去结账',
    OPTION:'选项',
    RESTAURANT_CLOSED:'商家休息了',
    RESTAURANT_CLOSED_LAH:'商家休息啦',
    ADD:'添加',
    UNIT:'份',
    SEARCH_RESTAURANTS_PLACEHOLDER:'搜索你想要的餐馆',
    CANNOT_FIND_ABOUT:'找不到关于',
    ABOUT_XX_ITEMS:'的东西哦',
    SEARCH:'搜索',

    //Login & Register & ResetPassword
    PLZ_ENTER_ACC_INFO: '请填写账户信息',
    INVALID_PASSWORD_LENGTH:'密码必须在8到32位之间',
    LOGIN_FAILED:'登录失败，请检查信息',
    PASSWORD_NOT_MATCHING:'密码配对不上 请重新输入',
    PLZ_ENTER_PHONE_NUM: '请填写正确手机号码',
    ALERT_CONGRA_TITLE:'恭喜',
    PASSWORD_RESET_SUCCESS:'密码重设成功',
    PLZ_ENTER_PASSWORD:'请填写密码',
    PASSWORD_NOT_THE_SAME:'两次密码不一样',

    //History
    PAID:'已支付',
    WAIT_FOR_RR_CONFIRM:'等待商家确认',
    REFUNDED:'已退款',
    ONLINE_PAYMENT_FAILED:'在线支付失败',
    PLZ_REORDER:'请重新下单',
    WAIT_FOR_PAYMENT:'等待支付',
    WAIT_FOR_PAYMENT_REMINDER:'若状态没有及时更改, 请手动下拉刷新',
    RESTAURANT_CONFIRMED:'商家已确认',
    PLZ_PICKUP:'请取餐',
    GETTING_RDY:'准备中',
    DRIVER_IS_OTW:'送餐员已开始送餐',
    DELIVERED:'已送到, 满意吗？',
    NEW_USER_CONFIRMING:'新用户订单确认中',
    CS_WILL_CONTACT:'客服稍后联系您改运费',
    DISH_OUT_OF_ORDER:'糟糕, 有的菜没了',
    ORDER_CANCELED:'订单已取消',

    //Comment
    CONFIRM_COMMENT:'确认评价',
    CANCEL:'取消',
    CHANGE_COMMENT:'更正',
    RATE_DELIVERY:'为配送打分',
    COMMENT_PLACEHOLDER:"写下您对司机的评价吧~",
    RESTAURANT_PLACEHOLDER:"写下您对商家的评价吧~",
    PLEASE_COMMENT:"请对送餐司机和餐馆打分",
    LIKE:'赞',
    DISLIKE:'踩',
    COMMENT:"评价",
    CM_DELIVERY: '小明配送',
    COMPLETE_TIME_PREFIX:'当日',
    COMPLETE_TIME_SUFFIX:'左右送达',
    ON_TIME:'准时',
    POLITE:"有礼貌",
    QUICK:"速度快",
    WELL_SERVERED:"服务周到",
    DELIVERY_TO_DOOR:"送货上门",
    WARM_DISH:"保温",
    WELL_PACKAGING:"包装完整",
    NICE_PACKAGING:"包装精美",
    WORTHY:"物美价廉",
    TASTY:"口味好",
    ECONOMICAL:"实惠",
    LARGE_AMOUNT:"分量足",


    //Card Type
    CREDIT_CARD:'信用卡',
    DEBIT_CARD:'借记卡',
    ALIPAY:'支付宝',
    CASH:'现金到付',
    CASH_SELF_PICKUP:'现金自取',
    CARD:'刷卡',
    APPLE_PAY:'Apple Pay',
    PAYMENT_TYPE:"支付方式",
    //About us
    ABOUT_US:'关于我们',

    //ALERT_TITLE
    ALERT_TITLE:'小明配送',
    ALERT_CONTENT:'您输入的支付信息输入有误',
    //HomeTab
    ORDER_BELOW:'在下面点餐呦',
    //MAIN_TAB
    ALERT_PAYMENT:'*通知: 即日起不支持到付刷卡，同时请勿使用Email Transfer(emt)，您可以使用Visa, Mastercard, Debit银行卡或者支付宝在线支付，或使用现金到付，谢谢~',
    ALERT_COMFIRM:'确定',
    COMFIRM_ADDRESS:'这是正确的地址吗？距离您的位置似乎有点远。',

    //Popup title
    REGISTER_FAIL:'注册失败, 请重新尝试',
    PHONE_IS_TAKEN:'该手机号码已注册',
    AUTH_FAIL:'验证失效,未知错误',
    VCODE_SENT:'验证码已发送',
    REACH_VCODE_MAX:'每天最多只能发送3次验证码',
    SEND_VCODE_FAIL:'验证码发送失败',
    PLZ_ENTER_PHONE_10:'请输入10位电话号码',
    PLZ_SELECT_REQUIRED_OPTION:'请选择必填选项',
    VERTIFICATION_FAIL_TITLE:'验证码错误',
    VERTIFICATION_FAIL_CONTENT:'请检查您输入的验证码',
    WECHAT_NO_PASSWORD:'微信用户无需密码, 请直接微信登录',
    UNKNOW_ERROR:'未知错误, 请联系客服',
    VCODE_SENT_TO_THIS_NUMBER:'验证码已发送手机上, 尾号为: '
}
