module.exports={
    //Starting
    MAIN_TAB:'Home',
    DELIVER_TO: 'Deliver to',
    SKIP:'Skip',
    APP_UPDATE_TITLE:'Update App',
    APP_UPDATE_CONTENT:'There is a newer version of this app, please update.',
    APP_UPDATE_CONFIRM:'Go',
    APP_UPDATE_CANCEL:'Later',

    //Searching
    AREA_SEARCH:'Category&Search',
    CITY_AREA:'City&Area',
    RES_TAG:'Category',
    MORE_TYPE:'More Categories',
    RETRACT:'Retract',
    //Setting
    MY_TAB:'My',
    SETTING:'Settings',
    MY_ORDER:'My Order',
    ADD_ADDRESS:'Add Address',
    SAVE_ADDRESS:'Save Address',
    CUSTOMER_SERVICE:'Contact Us',
    LANGUAGE_SETTING: 'Select Language',
    SWEETBOX: 'Sweetful Box, free shipping with purchase over $25',
    LOG_OUT: 'Log Out',

    //Order
    ORDER:'Order',
    ALL_ORDER:'All Orders',
    COMMENT:'Comments',
    YET_COMMENT:'Add Comments',
    ORDER_NO:'No.',
    PRICE:'Total',
    ACTUAL_PICE:'Actual Total',
    VERTIFICATION_CODE:'Get Code',
    NEW_CONFIRMING:'New User to be Confirmed',
    ENTER_VERTIFICATION_CODE:'Enter Code',
    RECIPT:'Recipt',
    HELP:'Help',
    SOLD_OUT:'Sold Out',
    REORDER:'Reorder',
    DETAIL:'Detail',
    DISH_QUANTITY:'Quantity',
    //Address
    ADDRESS:'Address',
    CONFIRM:'Comfirm',
    CHOOSE_ADDRESS:'Select Address',
    DELETE_ADDRESS:'Delete Address',
    ENTER_ADDRESS:'Enter Address',
    CHOOSE:'Select One',
    ADD_DEFAULT_ADDRESS:'Set as Default Address(Optional)',

    //Info
    CONTACT:'Name',
    PHONE:'Phone',


    //Check out
    ADD_PAYMENT:'Add Payment Method',
    PICK_UP:'Pick up',
    DELIVER:'Delivery',
    SET_DELIVER_FEE:'Set Delivery Fee',
    CHECK_OUT:'Check out',
    DELIVER_FEE:'Delivery Fee',
    PAY:'Payment',
    ONLINE_PAYMENT_WARNING: 'No refunds will be processed for customers that place orders through 3rd party WeChat services. Suspicious activities will be submitted to the police for investigation.',
    REMARK:'Remark',
    ADD_REMARK:'Add Remark(extra sauce, allergic)',
    TIPS:'Tips',
    TAXED_PRICE:'Price after Tax',
    PRETAX_PRICE:'Price before Tax',
    PRICE_SUBTOTAL:'Price Subtotal',
    PROMOTION:'Promotion',
    DISCOUNT:'Discount',
    CURRENT_USING:'Using',
    USE:'Apply',
    COUPON_CODE:'Promotion Code',
    COUPON_CODE_INVALID_REMINDER:'*Coupon code not available, cannot be used in this situation',
    INVALID_COUPON_CODE:'Invalid coupon code. Please check and retry',
    TAX:'Tax',
    SERVICE_FEE:'Service Fee',
    SERVICE_FEE_REMINDER:'No Extra Tips',
    CHARGE_TOTAL:'Final Price',
    ACTUAL_PAYING:'Charge',
    CONFIRM_ORDER:'Confirm Order',
    CONFIRM_PAY:'Confirm to Pay',
    RECENTLY_USE:'Recently Use',
    MORE_PAYMENT_WAY:'More Payment Methods',
    LONG_D_ORDER_REMINDER:"*Long distance delivery order. Please check the restaurant and delivery address.(Online payment order will be charged later.)",
    ALERT_ERROR_TITLE:'Something Wrong',
    CONFIRM_DELETE:'Confirm to Delete',
    PLZ_ENTER_COUPON:'Enter Promotion Coupon',
    ALERT_SERVICE_FEE_REMINDER:"Service fee contains online payment poundage, (includes credit card, debit card, Apple Pay and Alipay)and driver's service fee. No need to pay extra tips.",
    REMINDING:'Notice',
    ADD_CREDIT_CARD:'Add Credit Card',
    ADD_DEBIT_CARD:'Add Debit Card',
    CARD_NUMBER:'Card No.',
    EXPIRED_AT:'Expire Date',
    DELIVER_ADDRESS:'Delivery Address',

    //Menu
    GO_CHECKOUT:'Check Out',
    OPTION:'Option',
    RESTAURANT_CLOSED:'Restaurant Closed',
    RESTAURANT_CLOSED_LAH:'Restaurant Closed',
    ADD:'Add ',
    UNIT:' item(s)',
    SEARCH_RESTAURANTS_PLACEHOLDER:'Search Restaurants',
    CANNOT_FIND_ABOUT:'Cannot find anything about',
    ABOUT_XX_ITEMS:'',
    SEARCH:'Search',
    MUST_SELECT:'Required ',
    OPTIONAL_SELECT:'Optional ',
    DELETE:'Delete',
    CONFIRM_MODIFICATION:'Confirm Changes',

    //Login & Register & ResetPassword
    PLZ_ENTER_ACC_INFO: 'Please enter account information',
    INVALID_PASSWORD_LENGTH:'Password must between 8 to 32 words',
    LOGIN_FAILED:'Unable to login. Please check the information',
    PASSWORD_NOT_MATCHING:'Password not match confirmation, please try again',
    PLZ_ENTER_PHONE_NUM: 'Please enter a validate phone number',
    ALERT_CONGRA_TITLE:'Congratulation!',
    PASSWORD_RESET_SUCCESS:'Password Reset Success',
    PLZ_ENTER_PASSWORD:'Please Enter Password',

    //History
    REPAY:'Repay',
    PAID:'Paid',
    WAIT_FOR_RR_CONFIRM:'Waiting for Restaurant to Confirm',
    REFUNDED:'Refunded',
    ONLINE_PAYMENT_FAILED:'Online payment failed',
    PLZ_REPAY_AGAIN:'Please try again',
    PLZ_REORDER:'Please reorder',
    WAIT_FOR_PAYMENT:'Wait for Payment',
    WAIT_FOR_PAYMENT_REMINDER:'If the status not change in time, drag to refresh',
    RESTAURANT_CONFIRMED:'Restaurant Confirmed',
    PLZ_PICKUP:'Please Pick up',
    GETTING_RDY:'In Preparation',
    DRIVER_IS_OTW:'Driver on the Way',
    DELIVERED:'Delivered',
    NEW_USER_CONFIRMING:'New User Needs to be Confirmed',
    CS_WILL_CONTACT:'Customer Service Will Contact you about the Delivery Fee',
    DISH_OUT_OF_ORDER:'Dish Sold out',
    ORDER_CANCELED:'Order Canceled',

    //Comment
    CONFIRM_COMMENT:'Confirm',
    CANCEL:'Cancel',
    CHANGE_COMMENT:'Change Comment',
    RATE_DELIVERY:'Please rate the delivery',
    COMMENT_PLACEHOLDER:"Please write comments to our driver",
    RESTAURANT_PLACEHOLDER:"Please write comments to the restaurant",
    PLEASE_COMMENT:"Please write comments to our driver and restaurant",
    LIKE:'Like',
    DISLIKE:'Dislike',
    COMMENT:"Comment",
    CM_DELIVERY: 'Chanmao Driver',
    COMPLETE_TIME_PREFIX:'Today',
    COMPLETE_TIME_SUFFIX:'Arrived',
    ON_TIME:'On Time',
    POLITE:"Polite Service",
    QUICK:"Quick",
    WELL_SERVERED:"Well Servered",
    DELIVERY_TO_DOOR:"Delivery to Door",
    WARM_DISH:"Warm Dishes",
    WELL_PACKAGING:"Well Packed",
    NICE_PACKAGING:"Nice Packed",
    WORTHY:"Worthy",
    TASTY:"Tasty",
    ECONOMICAL:"Reasonable Prices",
    LARGE_AMOUNT:"Plentiful",


    //Card Type
    CREDIT_CARD:'Credit Card',
    DEBIT_CARD:'Debit Card',
    ALIPAY:'Alipay',
    CASH:'Cash',
    CASH_SELF_PICKUP:'Pick up',
    CARD:'Card',
    APPLE_PAY:'Apple Pay',
    PAYMENT_TYPE:"Payment Method",
    //About us
    ABOUT_US:'About Us',
    CHANMAO_INFO:'这是一个致力于打造多伦多最佳订餐平台，为自己理想奋斗的热血团队。我们愿真诚的接纳您的意见，也邀请志同道合的你加入我们。',
    CHANMAO_KEFU:'微信客服：chanmao_kefu',
    CHANMAO_BUSINESE:'商务合作：marketing@chanmao.ca',
    CHANMAO_COPYRIGHT:'Chanmao Inc. 版权所有',
    APP_VERSION:'版本号',

    //Alert title
    CHANMAO_REMINDING:'Chanmao Reminding You',
    ALERT_TITLE:'Chanmao',
    ALERT_CONTENT:'The information you entered is not correct',
    COPY_TO_CLIPBOARD:'Copied to clipboard',
    //HomeTab
    ORDER_BELOW:'Scroll Down to Order',
    //MAIN_TAB
    ALERT_PAYMENT:"*Notice: From now on we don't accept payment by card with drivers, and don't use Email Transfer as well. You can use online payment, including Visa, Mastercard, Debit Card, Apple Pay and Alipay, or cash. Thanks.",
    ALERT_COMFIRM:'Confirm',
    CONFIRM_ADDRESS:'Address correct？Seems far from your current location.',

    //Popup title
    REGISTER_FAIL:'Registration failed, please try again',
    PHONE_IS_TAKEN:'Phone number is registered',
    AUTH_FAIL:'Authorize failed, unknown mistake',
    VCODE_SENT:'Verification Code Sent',
    REACH_VCODE_MAX:'Sending Verification Code No More Than 3 Times a Day',
    SEND_VCODE_FAIL:'Sending Verification Code Failed',
    PLZ_ENTER_PHONE_10:'Please enter 10-digit phone number',
    PLZ_SELECT_REQUIRED_OPTION:'Please choose the required options',
    VERTIFICATION_FAIL_TITLE:'Wrong Validation Code',//(新用户用的)
    VERTIFICATION_FAIL_CONTENT:'Please check the code you entered',//(新用户用的)
}
